### ISSUE TITLE
Loading pretrained model

### ISSUE THREAD

**Issue by gandhirushabh2311** [hx173149/C3D-tensorflow#18]
I wanted to load the pretrained model which is in the form of a .model file. However as far as I know saved models in tensorflow are in the form of .meta files and can be loaded by tf.train.save_meta_files(). Can someone please let me know how can I load the graph from this model?

**Comment by geroge-gao** [comment]
@gandhirushabh2311 have you ever solved the problem?

**Comment by JulioEndara** [comment]
@geroge-gao download the .model files as per the instructions in readme file.

**Comment by JulioEndara** [comment]
@geroge-gao no I didn't have that issue.

**Comment by JulioEndara** [comment]
@geroge-gao I did follow the instructions as per readme file.

**Comment by geroge-gao** [comment]
@JulioEndara sorry to brother you,but this problem has troubled me for a few days, could I ask you a few questions on the email? my email is codergeroge@gmail.com

**Comment by JulioEndara** [comment]
@geroge-gao github is better than email because other people see the issue and they can help out rather than just one person, btw I'm not an expert on this so you are better off raising your issue to the community. 

Also this is also a closed issue.

I suggest you open a new issue and explain in detail what you are doing, what script you are executing and include full dump of your error... also confirm if you have modified the code or use it straight from the repo.
